--- # PROD.main.yml
name: Azure Deploy (PROD.main)
on: { push: { branches: [main] } }
jobs:
  deploy-prod-main:
    name: Build/Deploy (PROD.main)
    environment:
      name: PROD.main
      url: https://jimm.my
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Install Node
        id: node
        uses: actions/setup-node@v4
        with: { node-version: 22 }
      - name: Install Dependencies
        id: ci
        run: npm ci --loglevel=error --fund=false
      - name: Build SWA
        id: build
        run: npm run deploy
      - name: Copy Azure SWA Config
        id: config
        run: cp staticwebapp.config.json build
      - name: Deploy to Azure
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # https://aka.ms/swaworkflowconfig
          action: upload
          azure_static_web_apps_api_token: ${{secrets.AZ_SWA_API_TOKEN}}
          app_location: build
          is_static_export: true
          skip_api_build: true
          skip_app_build: true

...
